# Install OMERO.web on the IDR

# TODO: Add omeroweb hosts group
- hosts: "{{ idr_environment | default('idr') }}-omero-hosts"

  roles:
  - role: ome.redis
  - role: ome.omero_web

  # Vars are in group_vars/omero-hosts.yml

  environment: "{{ idr_ANSIBLE_ENVIRONMENT_VARIABLES | default({}) }}"

# deploy ms
# This will modify the omero web nginx configuration file
# It should be executed after running idr-omero-web.yml
# as it is in idr-01-install-idr.yml

- hosts: "{{ idr_environment | default('idr') }}-omeroreadonly-hosts"
  become: true

  roles:
  - role: ome.omero_ms_image_region

  environment: "{{ idr_ANSIBLE_ENVIRONMENT_VARIABLES | default({}) }}"
